version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.9.1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2048M
    volumes:
      # In production, we strongly recommend you set the path.data and path.
      # logs in elasticsearch.yml to locations outside of $ES_HOME.
      # Docker, Debian, and RPM installations write data and log to locations outside of $ES_HOME by default.
      - data:/var/data/elasticsearch
      - ./logs:/var/log/elasticsearch
    environment:
      # A node can only join a cluster when it shares its cluster.name with all the other nodes in the cluster.
      # The default name is elasticsearch, but you should change it to an appropriate name that describes the purpose of the cluster.
      - cluster.name=app
      # Elasticsearch uses node.name as a human-readable identifier for a particular instance of Elasticsearch.
      # This name is included in the response of many APIs
      - node.name=dev
      # If set to false, security features are disabled, which is not recommended.
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  data: